// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/proto.proto

package Bully

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationClient interface {
	CheckLeaderConn(ctx context.Context, in *CheckMessage, opts ...grpc.CallOption) (*CheckReturnMessage, error)
	NewCoordinator(ctx context.Context, in *CoordinaterMessage, opts ...grpc.CallOption) (*CoordinaterAckMessage, error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) CheckLeaderConn(ctx context.Context, in *CheckMessage, opts ...grpc.CallOption) (*CheckReturnMessage, error) {
	out := new(CheckReturnMessage)
	err := c.cc.Invoke(ctx, "/Bully.Replication/checkLeaderConn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationClient) NewCoordinator(ctx context.Context, in *CoordinaterMessage, opts ...grpc.CallOption) (*CoordinaterAckMessage, error) {
	out := new(CoordinaterAckMessage)
	err := c.cc.Invoke(ctx, "/Bully.Replication/newCoordinator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServer is the server API for Replication service.
// All implementations must embed UnimplementedReplicationServer
// for forward compatibility
type ReplicationServer interface {
	CheckLeaderConn(context.Context, *CheckMessage) (*CheckReturnMessage, error)
	NewCoordinator(context.Context, *CoordinaterMessage) (*CoordinaterAckMessage, error)
	mustEmbedUnimplementedReplicationServer()
}

// UnimplementedReplicationServer must be embedded to have forward compatible implementations.
type UnimplementedReplicationServer struct {
}

func (UnimplementedReplicationServer) CheckLeaderConn(context.Context, *CheckMessage) (*CheckReturnMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLeaderConn not implemented")
}
func (UnimplementedReplicationServer) NewCoordinator(context.Context, *CoordinaterMessage) (*CoordinaterAckMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewCoordinator not implemented")
}
func (UnimplementedReplicationServer) mustEmbedUnimplementedReplicationServer() {}

// UnsafeReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServer will
// result in compilation errors.
type UnsafeReplicationServer interface {
	mustEmbedUnimplementedReplicationServer()
}

func RegisterReplicationServer(s grpc.ServiceRegistrar, srv ReplicationServer) {
	s.RegisterService(&Replication_ServiceDesc, srv)
}

func _Replication_CheckLeaderConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).CheckLeaderConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Bully.Replication/checkLeaderConn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).CheckLeaderConn(ctx, req.(*CheckMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replication_NewCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinaterMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServer).NewCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Bully.Replication/newCoordinator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServer).NewCoordinator(ctx, req.(*CoordinaterMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Replication_ServiceDesc is the grpc.ServiceDesc for Replication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Bully.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "checkLeaderConn",
			Handler:    _Replication_CheckLeaderConn_Handler,
		},
		{
			MethodName: "newCoordinator",
			Handler:    _Replication_NewCoordinator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
